// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aswklowutruzcirofrzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzd2tsb3d1dHJ1emNpcm9mcnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODQzODYsImV4cCI6MjA2NzQ2MDM4Nn0.0r_M0Ok_EvIT32isvyZDYcaDEfH0RY33pjfMCRsNEKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});